import { MigrationInterface, QueryRunner  } from "typeorm"
import { City } from "../../entities/city";

export class createBahiaCities1681071535261 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        queryRunner
        .manager
        .createQueryBuilder()
        .insert()
        .into(City)
        .values([
            { state: { id: 5 }, value: 'Abaíra' },
            { state: { id: 5 }, value: 'Acajutiba' },
            { state: { id: 5 }, value: 'Adustina' },
            { state: { id: 5 }, value: 'Água Fria' },
            { state: { id: 5 }, value: 'Aiquara' },
            { state: { id: 5 }, value: 'Alagoinhas' },
            { state: { id: 5 }, value: 'Alcobaça' },
            { state: { id: 5 }, value: 'Almadina' },
            { state: { id: 5 }, value: 'Amargosa' },
            { state: { id: 5 }, value: 'Amélia Rodrigues' },
            { state: { id: 5 }, value: 'América Dourada' },
            { state: { id: 5 }, value: 'Anagé' },
            { state: { id: 5 }, value: 'Andaraí' },
            { state: { id: 5 }, value: 'Andorinha' },
            { state: { id: 5 }, value: 'Angical' },
            { state: { id: 5 }, value: 'Anguera' },
            { state: { id: 5 }, value: 'Antas' },
            { state: { id: 5 }, value: 'Antônio Cardoso' },
            { state: { id: 5 }, value: 'Antônio Gonçalves' },
            { state: { id: 5 }, value: 'Aporá' },
            { state: { id: 5 }, value: 'Apuarema' },
            { state: { id: 5 }, value: 'Aracatu' },
            { state: { id: 5 }, value: 'Araci' },
            { state: { id: 5 }, value: 'Aramari' },
            { state: { id: 5 }, value: 'Arataca' },
            { state: { id: 5 }, value: 'Aratuípe' },
            { state: { id: 5 }, value: 'Araçás' },
            { state: { id: 5 }, value: 'Aurelino Leal' },
            { state: { id: 5 }, value: 'Baianópolis' },
            { state: { id: 5 }, value: 'Baixa Grande' },
            { state: { id: 5 }, value: 'Banzaê' },
            { state: { id: 5 }, value: 'Barra' },
            { state: { id: 5 }, value: 'Barra da Estiva' },
            { state: { id: 5 }, value: 'Barra do Choça' },
            { state: { id: 5 }, value: 'Barra do Mendes' },
            { state: { id: 5 }, value: 'Barra do Rocha' },
            { state: { id: 5 }, value: 'Barreiras' },
            { state: { id: 5 }, value: 'Barro Alto' },
            { state: { id: 5 }, value: 'Barro Preto' },
            { state: { id: 5 }, value: 'Barrocas' },
            { state: { id: 5 }, value: 'Belmonte' },
            { state: { id: 5 }, value: 'Belo Campo' },
            { state: { id: 5 }, value: 'Biritinga' },
            { state: { id: 5 }, value: 'Boa Nova' },
            { state: { id: 5 }, value: 'Boa Vista do Tupim' },
            { state: { id: 5 }, value: 'Bom Jesus da Lapa' },
            { state: { id: 5 }, value: 'Bom Jesus da Serra' },
            { state: { id: 5 }, value: 'Boninal' },
            { state: { id: 5 }, value: 'Bonito' },
            { state: { id: 5 }, value: 'Boquira' },
            { state: { id: 5 }, value: 'Botuporã' },
            { state: { id: 5 }, value: 'Brejolândia' },
            { state: { id: 5 }, value: 'Brejões' },
            { state: { id: 5 }, value: 'Brotas de Macaúbas' },
            { state: { id: 5 }, value: 'Brumado' },
            { state: { id: 5 }, value: 'Buerarema' },
            { state: { id: 5 }, value: 'Buritirama' },
            { state: { id: 5 }, value: 'Caatiba' },
            { state: { id: 5 }, value: 'Cabaceiras do Paraguaçu' },
            { state: { id: 5 }, value: 'Cachoeira' },
            { state: { id: 5 }, value: 'Caculé' },
            { state: { id: 5 }, value: 'Caetanos' },
            { state: { id: 5 }, value: 'Caetité' },
            { state: { id: 5 }, value: 'Cafarnaum' },
            { state: { id: 5 }, value: 'Cairu' },
            { state: { id: 5 }, value: 'Caldeirão Grande' },
            { state: { id: 5 }, value: 'Camacan' },
            { state: { id: 5 }, value: 'Camamu' },
            { state: { id: 5 }, value: 'Camaçari' },
            { state: { id: 5 }, value: 'Campo Alegre de Lourdes' },
            { state: { id: 5 }, value: 'Campo Formoso' },
            { state: { id: 5 }, value: 'Canarana' },
            { state: { id: 5 }, value: 'Canavieiras' },
            { state: { id: 5 }, value: 'Candeal' },
            { state: { id: 5 }, value: 'Candeias' },
            { state: { id: 5 }, value: 'Candiba' },
            { state: { id: 5 }, value: 'Cansanção' },
            { state: { id: 5 }, value: 'Canudos' },
            { state: { id: 5 }, value: 'Canápolis' },
            { state: { id: 5 }, value: 'Capela do Alto Alegre' },
            { state: { id: 5 }, value: 'Capim Grosso' },
            { state: { id: 5 }, value: 'Caravelas' },
            { state: { id: 5 }, value: 'Caraíbas' },
            { state: { id: 5 }, value: 'Cardeal da Silva' },
            { state: { id: 5 }, value: 'Carinhanha' },
            { state: { id: 5 }, value: 'Casa Nova' },
            { state: { id: 5 }, value: 'Castro Alves' },
            { state: { id: 5 }, value: 'Catolândia' },
            { state: { id: 5 }, value: 'Catu' },
            { state: { id: 5 }, value: 'Caturama' },
            { state: { id: 5 }, value: 'Caém' },
            { state: { id: 5 }, value: 'Central' },
            { state: { id: 5 }, value: 'Chorrochó' },
            { state: { id: 5 }, value: 'Cipó' },
            { state: { id: 5 }, value: 'Coaraci' },
            { state: { id: 5 }, value: 'Cocos' },
            { state: { id: 5 }, value: 'Conceição da Feira' },
            { state: { id: 5 }, value: 'Conceição do Almeida' },
            { state: { id: 5 }, value: 'Conceição do Coité' },
            { state: { id: 5 }, value: 'Conceição do Jacuípe' },
            { state: { id: 5 }, value: 'Conde' },
            { state: { id: 5 }, value: 'Condeúba' },
            { state: { id: 5 }, value: 'Contendas do Sincorá' },
            { state: { id: 5 }, value: 'Coração de Maria' },
            { state: { id: 5 }, value: 'Cordeiros' },
            { state: { id: 5 }, value: 'Coribe' },
            { state: { id: 5 }, value: 'Coronel João Sá' },
            { state: { id: 5 }, value: 'Correntina' },
            { state: { id: 5 }, value: 'Cotegipe' },
            { state: { id: 5 }, value: 'Cravolândia' },
            { state: { id: 5 }, value: 'Cristópolis' },
            { state: { id: 5 }, value: 'Crisópolis' },
            { state: { id: 5 }, value: 'Cruz das Almas' },
            { state: { id: 5 }, value: 'Curaçá' },
            { state: { id: 5 }, value: 'Cândido Sales' },
            { state: { id: 5 }, value: 'Cícero Dantas' },
            { state: { id: 5 }, value: "Dias d'Ávila" },
            { state: { id: 5 }, value: 'Dom Basílio' },
            { state: { id: 5 }, value: 'Dom Macedo Costa' },
            { state: { id: 5 }, value: 'Dário Meira' },
            { state: { id: 5 }, value: 'Elísio Medrado' },
            { state: { id: 5 }, value: 'Encruzilhada' },
            { state: { id: 5 }, value: 'Entre Rios' },
            { state: { id: 5 }, value: 'Érico Cardoso' },
            { state: { id: 5 }, value: 'Esplanada' },
            { state: { id: 5 }, value: 'Euclides da Cunha' },
            { state: { id: 5 }, value: 'Eunápolis' },
            { state: { id: 5 }, value: 'Feira da Mata' },
            { state: { id: 5 }, value: 'Feira de Santana' },
            { state: { id: 5 }, value: 'Filadélfia' },
            { state: { id: 5 }, value: 'Firmino Alves' },
            { state: { id: 5 }, value: 'Floresta Azul' },
            { state: { id: 5 }, value: 'Formosa do Rio Preto' },
            { state: { id: 5 }, value: 'Fátima' },
            { state: { id: 5 }, value: 'Gandu' },
            { state: { id: 5 }, value: 'Gavião' },
            { state: { id: 5 }, value: 'Gentio do Ouro' },
            { state: { id: 5 }, value: 'Glória' },
            { state: { id: 5 }, value: 'Gongogi' },
            { state: { id: 5 }, value: 'Governador Mangabeira' },
            { state: { id: 5 }, value: 'Guajeru' },
            { state: { id: 5 }, value: 'Guanambi' },
            { state: { id: 5 }, value: 'Guaratinga' },
            { state: { id: 5 }, value: 'Heliópolis' },
            { state: { id: 5 }, value: 'Iaçu' },
            { state: { id: 5 }, value: 'Ibiassucê' },
            { state: { id: 5 }, value: 'Ibicaraí' },
            { state: { id: 5 }, value: 'Ibicoara' },
            { state: { id: 5 }, value: 'Ibicuí' },
            { state: { id: 5 }, value: 'Ibipeba' },
            { state: { id: 5 }, value: 'Ibipitanga' },
            { state: { id: 5 }, value: 'Ibiquera' },
            { state: { id: 5 }, value: 'Ibirapitanga' },
            { state: { id: 5 }, value: 'Ibirapuã' },
            { state: { id: 5 }, value: 'Ibirataia' },
            { state: { id: 5 }, value: 'Ibitiara' },
            { state: { id: 5 }, value: 'Ibititá' },
            { state: { id: 5 }, value: 'Ibotirama' },
            { state: { id: 5 }, value: 'Ichu' },
            { state: { id: 5 }, value: 'Igaporã' },
            { state: { id: 5 }, value: 'Igrapiúna' },
            { state: { id: 5 }, value: 'Iguaí' },
            { state: { id: 5 }, value: 'Ilhéus' },
            { state: { id: 5 }, value: 'Inhambupe' },
            { state: { id: 5 }, value: 'Ipecaetá' },
            { state: { id: 5 }, value: 'Ipiaú' },
            { state: { id: 5 }, value: 'Ipirá' },
            { state: { id: 5 }, value: 'Ipupiara' },
            { state: { id: 5 }, value: 'Irajuba' },
            { state: { id: 5 }, value: 'Iramaia' },
            { state: { id: 5 }, value: 'Iraquara' },
            { state: { id: 5 }, value: 'Irará' },
            { state: { id: 5 }, value: 'Irecê' },
            { state: { id: 5 }, value: 'Itabela' },
            { state: { id: 5 }, value: 'Itaberaba' },
            { state: { id: 5 }, value: 'Itabuna' },
            { state: { id: 5 }, value: 'Itacaré' },
            { state: { id: 5 }, value: 'Itaetê' },
            { state: { id: 5 }, value: 'Itagi' },
            { state: { id: 5 }, value: 'Itagibá' },
            { state: { id: 5 }, value: 'Itagimirim' },
            { state: { id: 5 }, value: 'Itaguaçu da Bahia' },
            { state: { id: 5 }, value: 'Itaju do Colônia' },
            { state: { id: 5 }, value: 'Itajuípe' },
            { state: { id: 5 }, value: 'Itamaraju' },
            { state: { id: 5 }, value: 'Itamari' },
            { state: { id: 5 }, value: 'Itambé' },
            { state: { id: 5 }, value: 'Itanagra' },
            { state: { id: 5 }, value: 'Itanhém' },
            { state: { id: 5 }, value: 'Itaparica' },
            { state: { id: 5 }, value: 'Itapebi' },
            { state: { id: 5 }, value: 'Itapetinga' },
            { state: { id: 5 }, value: 'Itapicuru' },
            { state: { id: 5 }, value: 'Itapitanga' },
            { state: { id: 5 }, value: 'Itapé' },
            { state: { id: 5 }, value: 'Itaquara' },
            { state: { id: 5 }, value: 'Itarantim' },
            { state: { id: 5 }, value: 'Itatim' },
            { state: { id: 5 }, value: 'Itiruçu' },
            { state: { id: 5 }, value: 'Itiúba' },
            { state: { id: 5 }, value: 'Itororó' },
            { state: { id: 5 }, value: 'Ituaçu' },
            { state: { id: 5 }, value: 'Ituberá' },
            { state: { id: 5 }, value: 'Iuiú' },
            { state: { id: 5 }, value: 'Jaborandi' },
            { state: { id: 5 }, value: 'Jacaraci' },
            { state: { id: 5 }, value: 'Jacobina' },
            { state: { id: 5 }, value: 'Jaguaquara' },
            { state: { id: 5 }, value: 'Jaguarari' },
            { state: { id: 5 }, value: 'Jaguaripe' },
            { state: { id: 5 }, value: 'Jandaíra' },
            { state: { id: 5 }, value: 'Jequié' },
            { state: { id: 5 }, value: 'Jeremoabo' },
            { state: { id: 5 }, value: 'Jiquiriçá' },
            { state: { id: 5 }, value: 'Jitaúna' },
            { state: { id: 5 }, value: 'João Dourado' },
            { state: { id: 5 }, value: 'Juazeiro' },
            { state: { id: 5 }, value: 'Jucuruçu' },
            { state: { id: 5 }, value: 'Jussara' },
            { state: { id: 5 }, value: 'Jussari' },
            { state: { id: 5 }, value: 'Jussiape' },
            { state: { id: 5 }, value: 'Lafaiete Coutinho' },
            { state: { id: 5 }, value: 'Lagoa Real' },
            { state: { id: 5 }, value: 'Laje' },
            { state: { id: 5 }, value: 'Lajedinho' },
            { state: { id: 5 }, value: 'Lajedo do Tabocal' },
            { state: { id: 5 }, value: 'Lajedão' },
            { state: { id: 5 }, value: 'Lamarão' },
            { state: { id: 5 }, value: 'Lapão' },
            { state: { id: 5 }, value: 'Lauro de Freitas' },
            { state: { id: 5 }, value: 'Lençóis' },
            { state: { id: 5 }, value: 'Licínio de Almeida' },
            { state: { id: 5 }, value: 'Livramento de Nossa Senhora' },
            { state: { id: 5 }, value: 'Luís Eduardo Magalhães' },
            { state: { id: 5 }, value: 'Macajuba' },
            { state: { id: 5 }, value: 'Macarani' },
            { state: { id: 5 }, value: 'Macaúbas' },
            { state: { id: 5 }, value: 'Macururé' },
            { state: { id: 5 }, value: 'Madre de Deus' },
            { state: { id: 5 }, value: 'Maetinga' },
            { state: { id: 5 }, value: 'Maiquinique' },
            { state: { id: 5 }, value: 'Mairi' },
            { state: { id: 5 }, value: 'Malhada' },
            { state: { id: 5 }, value: 'Malhada de Pedras' },
            { state: { id: 5 }, value: 'Manoel Vitorino' },
            { state: { id: 5 }, value: 'Mansidão' },
            { state: { id: 5 }, value: 'Maracás' },
            { state: { id: 5 }, value: 'Maragogipe' },
            { state: { id: 5 }, value: 'Maraú' },
            { state: { id: 5 }, value: 'Marcionílio Souza' },
            { state: { id: 5 }, value: 'Mascote' },
            { state: { id: 5 }, value: 'Mata de São João' },
            { state: { id: 5 }, value: 'Matina' },
            { state: { id: 5 }, value: 'Medeiros Neto' },
            { state: { id: 5 }, value: 'Miguel Calmon' },
            { state: { id: 5 }, value: 'Milagres' },
            { state: { id: 5 }, value: 'Mirangaba' },
            { state: { id: 5 }, value: 'Mirante' },
            { state: { id: 5 }, value: 'Monte Santo' },
            { state: { id: 5 }, value: 'Morpará' },
            { state: { id: 5 }, value: 'Morro do Chapéu' },
            { state: { id: 5 }, value: 'Mortugaba' },
            { state: { id: 5 }, value: 'Mucugê' },
            { state: { id: 5 }, value: 'Mucuri' },
            { state: { id: 5 }, value: 'Mulungu do Morro' },
            { state: { id: 5 }, value: 'Mundo Novo' },
            { state: { id: 5 }, value: 'Muniz Ferreira' },
            { state: { id: 5 }, value: 'Muquém de São Francisco' },
            { state: { id: 5 }, value: 'Muritiba' },
            { state: { id: 5 }, value: 'Mutuípe' },
            { state: { id: 5 }, value: 'Nazaré' },
            { state: { id: 5 }, value: 'Nilo Peçanha' },
            { state: { id: 5 }, value: 'Nordestina' },
            { state: { id: 5 }, value: 'Nova Canaã' },
            { state: { id: 5 }, value: 'Nova Fátima' },
            { state: { id: 5 }, value: 'Nova Ibiá' },
            { state: { id: 5 }, value: 'Nova Itarana' },
            { state: { id: 5 }, value: 'Nova Redenção' },
            { state: { id: 5 }, value: 'Nova Soure' },
            { state: { id: 5 }, value: 'Nova Viçosa' },
            { state: { id: 5 }, value: 'Novo Horizonte' },
            { state: { id: 5 }, value: 'Novo Triunfo' },
            { state: { id: 5 }, value: 'Olindina' },
            { state: { id: 5 }, value: 'Oliveira dos Brejinhos' },
            { state: { id: 5 }, value: 'Ouriçangas' },
            { state: { id: 5 }, value: 'Ourolândia' },
            { state: { id: 5 }, value: 'Palmas de Monte Alto' },
            { state: { id: 5 }, value: 'Palmeiras' },
            { state: { id: 5 }, value: 'Paramirim' },
            { state: { id: 5 }, value: 'Paratinga' },
            { state: { id: 5 }, value: 'Paripiranga' },
            { state: { id: 5 }, value: 'Pau Brasil' },
            { state: { id: 5 }, value: 'Paulo Afonso' },
            { state: { id: 5 }, value: 'Pedro Alexandre' },
            { state: { id: 5 }, value: 'Pedrão' },
            { state: { id: 5 }, value: 'Piatã' },
            { state: { id: 5 }, value: 'Pilão Arcado' },
            { state: { id: 5 }, value: 'Pindaí' },
            { state: { id: 5 }, value: 'Pindobaçu' },
            { state: { id: 5 }, value: 'Pintadas' },
            { state: { id: 5 }, value: 'Piraí do Norte' },
            { state: { id: 5 }, value: 'Piripá' },
            { state: { id: 5 }, value: 'Piritiba' },
            { state: { id: 5 }, value: 'Planaltino' },
            { state: { id: 5 }, value: 'Planalto' },
            { state: { id: 5 }, value: 'Pojuca' },
            { state: { id: 5 }, value: 'Ponto Novo' },
            { state: { id: 5 }, value: 'Porto Seguro' },
            { state: { id: 5 }, value: 'Potiraguá' },
            { state: { id: 5 }, value: 'Poções' },
            { state: { id: 5 }, value: 'Prado' },
            { state: { id: 5 }, value: 'Presidente Dutra' },
            { state: { id: 5 }, value: 'Presidente Jânio Quadros' },
            { state: { id: 5 }, value: 'Presidente Tancredo Neves' },
            { state: { id: 5 }, value: 'Pé de Serra' },
            { state: { id: 5 }, value: 'Queimadas' },
            { state: { id: 5 }, value: 'Quijingue' },
            { state: { id: 5 }, value: 'Quixabeira' },
            { state: { id: 5 }, value: 'Rafael Jambeiro' },
            { state: { id: 5 }, value: 'Remanso' },
            { state: { id: 5 }, value: 'Retirolândia' },
            { state: { id: 5 }, value: 'Riacho de Santana' },
            { state: { id: 5 }, value: 'Riachão das Neves' },
            { state: { id: 5 }, value: 'Riachão do Jacuípe' },
            { state: { id: 5 }, value: 'Ribeira do Amparo' },
            { state: { id: 5 }, value: 'Ribeira do Pombal' },
            { state: { id: 5 }, value: 'Ribeirão do Largo' },
            { state: { id: 5 }, value: 'Rio de Contas' },
            { state: { id: 5 }, value: 'Rio do Antônio' },
            { state: { id: 5 }, value: 'Rio do Pires' },
            { state: { id: 5 }, value: 'Rio Real' },
            { state: { id: 5 }, value: 'Rodelas' },
            { state: { id: 5 }, value: 'Ruy Barbosa' },
            { state: { id: 5 }, value: 'Salinas da Margarida' },
            { state: { id: 5 }, value: 'Salvador' },
            { state: { id: 5 }, value: 'Santa Brígida' },
            { state: { id: 5 }, value: 'Santa Bárbara' },
            { state: { id: 5 }, value: 'Santa Cruz Cabrália' },
            { state: { id: 5 }, value: 'Santa Cruz da Vitória' },
            { state: { id: 5 }, value: 'Santa Inês' },
            { state: { id: 5 }, value: 'Santa Luzia' },
            { state: { id: 5 }, value: 'Santa Maria da Vitória' },
            { state: { id: 5 }, value: 'Santa Rita de Cássia' },
            { state: { id: 5 }, value: 'Santa Teresinha' },
            { state: { id: 5 }, value: 'Santaluz' },
            { state: { id: 5 }, value: 'Santana' },
            { state: { id: 5 }, value: 'Santanópolis' },
            { state: { id: 5 }, value: 'Santo Amaro' },
            { state: { id: 5 }, value: 'Santo Antônio de Jesus' },
            { state: { id: 5 }, value: 'Santo Estêvão' },
            { state: { id: 5 }, value: 'Sapeaçu' },
            { state: { id: 5 }, value: 'Saubara' },
            { state: { id: 5 }, value: 'Saúde' },
            { state: { id: 5 }, value: 'Seabra' },
            { state: { id: 5 }, value: 'Sebastião Laranjeiras' },
            { state: { id: 5 }, value: 'Senhor do Bonfim' },
            { state: { id: 5 }, value: 'Sento Sé' },
            { state: { id: 5 }, value: 'Serra do Ramalho' },
            { state: { id: 5 }, value: 'Serra Dourada' },
            { state: { id: 5 }, value: 'Serra Preta' },
            { state: { id: 5 }, value: 'Serrinha' },
            { state: { id: 5 }, value: 'Serrolândia' },
            { state: { id: 5 }, value: 'Simões Filho' },
            { state: { id: 5 }, value: 'Sobradinho' },
            { state: { id: 5 }, value: 'Souto Soares' },
            { state: { id: 5 }, value: 'Sátiro Dias' },
            { state: { id: 5 }, value: 'São Desidério' },
            { state: { id: 5 }, value: 'São Domingos' },
            { state: { id: 5 }, value: 'São Felipe' },
            { state: { id: 5 }, value: 'São Francisco do Conde' },
            { state: { id: 5 }, value: 'São Félix' },
            { state: { id: 5 }, value: 'São Félix do Coribe' },
            { state: { id: 5 }, value: 'São Gabriel' },
            { state: { id: 5 }, value: 'São Gonçalo dos Campos' },
            { state: { id: 5 }, value: 'São José da Vitória' },
            { state: { id: 5 }, value: 'São José do Jacuípe' },
            { state: { id: 5 }, value: 'São Miguel das Matas' },
            { state: { id: 5 }, value: 'São Sebastião do Passé' },
            { state: { id: 5 }, value: 'Sítio do Mato' },
            { state: { id: 5 }, value: 'Sítio do Quinto' },
            { state: { id: 5 }, value: 'Tabocas do Brejo Velho' },
            { state: { id: 5 }, value: 'Tanhaçu' },
            { state: { id: 5 }, value: 'Tanque Novo' },
            { state: { id: 5 }, value: 'Tanquinho' },
            { state: { id: 5 }, value: 'Taperoá' },
            { state: { id: 5 }, value: 'Tapiramutá' },
            { state: { id: 5 }, value: 'Teixeira de Freitas' },
            { state: { id: 5 }, value: 'Teodoro Sampaio' },
            { state: { id: 5 }, value: 'Teofilândia' },
            { state: { id: 5 }, value: 'Teolândia' },
            { state: { id: 5 }, value: 'Terra Nova' },
            { state: { id: 5 }, value: 'Tremedal' },
            { state: { id: 5 }, value: 'Tucano' },
            { state: { id: 5 }, value: 'Uauá' },
            { state: { id: 5 }, value: 'Ubaitaba' },
            { state: { id: 5 }, value: 'Ubatã' },
            { state: { id: 5 }, value: 'Ubaíra' },
            { state: { id: 5 }, value: 'Uibaí' },
            { state: { id: 5 }, value: 'Umburanas' },
            { state: { id: 5 }, value: 'Una' },
            { state: { id: 5 }, value: 'Urandi' },
            { state: { id: 5 }, value: 'Uruçuca' },
            { state: { id: 5 }, value: 'Utinga' },
            { state: { id: 5 }, value: 'Valente' },
            { state: { id: 5 }, value: 'Valença' },
            { state: { id: 5 }, value: 'Varzedo' },
            { state: { id: 5 }, value: 'Vera Cruz' },
            { state: { id: 5 }, value: 'Vereda' },
            { state: { id: 5 }, value: 'Vitória da Conquista' },
            { state: { id: 5 }, value: 'Várzea da Roça' },
            { state: { id: 5 }, value: 'Várzea do Poço' },
            { state: { id: 5 }, value: 'Várzea Nova' },
            { state: { id: 5 }, value: 'Wagner' },
            { state: { id: 5 }, value: 'Wanderley' },
            { state: { id: 5 }, value: 'Wenceslau Guimarães' }
        ])
        .execute();
     }

    public async down(queryRunner: QueryRunner): Promise<void> {
     }

 }
